language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jimbobukii/docker-react -f Dockerfiledev .

script:
  - docker run -e CI=true jimbobukii/docker-react npm run test -- --coverage

